[package]
authors = ["Erik Johnston"]
edition = "2018"
name = "casniam"
version = "0.1.0"

[dependencies]
failure = "0.1.2"
petgraph = "0.4.13"
serde_json = "1.0.27"
tokio = "0.1.11"
tokio-async-await = "0.1.0"
futures-preview = "0.3.0-alpha.5"
serde = "1.0.84"
serde_derive = "1.0.84"
